# NumPy Operations Notebook
This notebook contains detailed examples of various NumPy operations, including array creation, indexing, slicing, broadcasting, and more.

## 1. Array Creation

In [1]:
import numpy as np

In [2]:
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:

# Create arrays of various types
# One-dimensional array
one_d_array = np.array([1, 2, 3, 4, 5])
print("One-dimensional array:")
print(one_d_array)

# Two-dimensional array
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("\nTwo-dimensional array:")
print(two_d_array)

# Three-dimensional array
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nThree-dimensional array:")
print(three_d_array)


One-dimensional array:
[1 2 3 4 5]

Two-dimensional array:
[[1 2 3]
 [4 5 6]]

Three-dimensional array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Attributes
- shape: Tuple representing the dimensions of the array.
- ndim: Number of dimensions (axes) in the array.
- size: Total number of elements in the array.
- dtype: Data type of elements in the array.
- itemsize: Size of a single element in bytes.
- nbytes: Total memory consumption of the array.
- flags: Shows detailed memory layout, including contiguity (C-style or Fortran-style).

In [10]:
# Creating an example array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int32)

# Display the array
print("Array:")
print(arr)

# Demonstrating various array attributes

# Shape of the array (dimensions)
print("\nShape of the array (rows, columns):", arr.shape)

# Number of dimensions
print("Number of dimensions (ndim):", arr.ndim)

# Total number of elements in the array
print("Total number of elements (size):", arr.size)

# Data type of elements
print("Data type of elements (dtype):", arr.dtype)

# Size in bytes of each element
print("Size of each element in bytes (itemsize):", arr.itemsize)

# Total size of the array in bytes
print("Total array size in bytes (nbytes):", arr.nbytes)

# Memory layout of the array
print("\nFlags showing memory layout of the array:")
print(arr.flags)

# Example of modifying the shape
print("\nReshaped array (using shape):")
arr.shape = (1, 9)
print(arr)

# Resetting the shape
arr.shape = (3, 3)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of the array (rows, columns): (3, 3)
Number of dimensions (ndim): 2
Total number of elements (size): 9
Data type of elements (dtype): int32
Size of each element in bytes (itemsize): 4
Total array size in bytes (nbytes): 36

Flags showing memory layout of the array:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False


Reshaped array (using shape):
[[1 2 3 4 5 6 7 8 9]]


## Reshaping

In [5]:
import numpy as np
a=np.array([1, 2, 3,4,5], ndmin=2) # minimum dimensions
b = np.array([1, 2, 3], dtype=complex) # dtype parameter
c=np.array([[1,2,3],[4,5,6]])
c.shape=(3,2)
d = c.reshape(2,3)
e = np.arange(24)
f = np.zeros(5)
print (a)
print (b)
print (c)
print (d)
print (e)
print (e.flags)

[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## Special Arrays

In [11]:
# numpy.empty: Creates an uninitialized array
# The elements in this array will contain arbitrary values (not initialized)
empty_array = np.empty((3, 3), dtype=np.float32)
print("Empty Array (3x3, uninitialized):")
print(empty_array)

# numpy.zeros: Creates an array filled with zeros
zeros_array = np.zeros((3, 3), dtype=np.int32)
print("\nZeros Array (3x3, filled with 0s):")
print(zeros_array)

# numpy.ones: Creates an array filled with ones
ones_array = np.ones((3, 3), dtype=np.float64)
print("\nOnes Array (3x3, filled with 1s):")
print(ones_array)

# numpy.empty with custom shape and type
empty_array_custom = np.empty((2, 5), dtype=np.int64)
print("\nEmpty Array (2x5, dtype=int64, uninitialized):")
print(empty_array_custom)

# numpy.zeros with a higher-dimensional shape
zeros_array_3d = np.zeros((2, 3, 4), dtype=np.float16)
print("\nZeros Array (3D, shape (2, 3, 4), filled with 0s):")
print(zeros_array_3d)

# numpy.ones with a higher-dimensional shape
ones_array_3d = np.ones((2, 3, 4), dtype=np.float32)
print("\nOnes Array (3D, shape (2, 3, 4), filled with 1s):")
print(ones_array_3d)


Empty Array (3x3, uninitialized):
[[5.7857652e-39 8.4489539e-39 1.0193848e-38]
 [1.0102069e-38 7.3470022e-39 9.6428826e-39]
 [1.0653072e-38 8.9081510e-39 8.9081973e-39]]

Zeros Array (3x3, filled with 0s):
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones Array (3x3, filled with 1s):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Empty Array (2x5, dtype=int64, uninitialized):
[[               0                0                0                0
                 0]
 [               0                0                0                0
  2251801531514880]]

Zeros Array (3D, shape (2, 3, 4), filled with 0s):
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

Ones Array (3D, shape (2, 3, 4), filled with 1s):
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## Indexing and Slicing

In [11]:

# Create an array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
# Indexing
print("Element at position (1, 2):", arr[2, 2])

# Slicing
print("\nFirst two rows:")
print(arr[:2])

print("\nLast two columns:")
print(arr[:, -2:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at position (1, 2): 9

First two rows:
[[1 2 3]
 [4 5 6]]

Last two columns:
[[2 3]
 [5 6]
 [8 9]]


## Data Types

In [9]:
# Boolean data type
bool_array = np.array([True, False, True], dtype=np.bool_)
print("Boolean Array:", bool_array, "| Data Type:", bool_array.dtype)

# Default integer type
int_default = np.array([1, 2, 3], dtype=np.int_)
print("Default Integer Array:", int_default, "| Data Type:", int_default.dtype)

# Integer types
intc_array = np.array([1, 2, 3], dtype=np.intc)
print("C Integer Array:", intc_array, "| Data Type:", intc_array.dtype)

intp_array = np.array([1, 2, 3], dtype=np.intp)
print("Index Integer Array:", intp_array, "| Data Type:", intp_array.dtype)

int8_array = np.array([-128, 127], dtype=np.int8)
print("Int8 Array:", int8_array, "| Data Type:", int8_array.dtype)

int16_array = np.array([-32768, 32767], dtype=np.int16)
print("Int16 Array:", int16_array, "| Data Type:", int16_array.dtype)

int32_array = np.array([-2147483648, 2147483647], dtype=np.int32)
print("Int32 Array:", int32_array, "| Data Type:", int32_array.dtype)

int64_array = np.array([-9223372036854775808, 9223372036854775807], dtype=np.int64)
print("Int64 Array:", int64_array, "| Data Type:", int64_array.dtype)

# Unsigned integers
uint8_array = np.array([0, 255], dtype=np.uint8)
print("UInt8 Array:", uint8_array, "| Data Type:", uint8_array.dtype)

uint16_array = np.array([0, 65535], dtype=np.uint16)
print("UInt16 Array:", uint16_array, "| Data Type:", uint16_array.dtype)

uint32_array = np.array([0, 4294967295], dtype=np.uint32)
print("UInt32 Array:", uint32_array, "| Data Type:", uint32_array.dtype)

uint64_array = np.array([0, 18446744073709551615], dtype=np.uint64)
print("UInt64 Array:", uint64_array, "| Data Type:", uint64_array.dtype)

# Floating-point types
float_default = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print("Default Float Array:", float_default, "| Data Type:", float_default.dtype)

float16_array = np.array([1.1, 2.2, 3.3], dtype=np.float16)
print("Float16 Array:", float16_array, "| Data Type:", float16_array.dtype)

float32_array = np.array([1.1, 2.2, 3.3], dtype=np.float32)
print("Float32 Array:", float32_array, "| Data Type:", float32_array.dtype)

float64_array = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print("Float64 Array:", float64_array, "| Data Type:", float64_array.dtype)

# Complex types
complex_default = np.array([1+2j, 3+4j], dtype=np.complex128)
print("Default Complex Array:", complex_default, "| Data Type:", complex_default.dtype)

complex64_array = np.array([1+2j, 3+4j], dtype=np.complex64)
print("Complex64 Array:", complex64_array, "| Data Type:", complex64_array.dtype)

complex128_array = np.array([1+2j, 3+4j], dtype=np.complex128)
print("Complex128 Array:", complex128_array, "| Data Type:", complex128_array.dtype)

Boolean Array: [ True False  True] | Data Type: bool
Default Integer Array: [1 2 3] | Data Type: int64
C Integer Array: [1 2 3] | Data Type: int32
Index Integer Array: [1 2 3] | Data Type: int64
Int8 Array: [-128  127] | Data Type: int8
Int16 Array: [-32768  32767] | Data Type: int16
Int32 Array: [-2147483648  2147483647] | Data Type: int32
Int64 Array: [-9223372036854775808  9223372036854775807] | Data Type: int64
UInt8 Array: [  0 255] | Data Type: uint8
UInt16 Array: [    0 65535] | Data Type: uint16
UInt32 Array: [         0 4294967295] | Data Type: uint32
UInt64 Array: [                   0 18446744073709551615] | Data Type: uint64
Default Float Array: [1.1 2.2 3.3] | Data Type: float64
Float16 Array: [1.1 2.2 3.3] | Data Type: float16
Float32 Array: [1.1 2.2 3.3] | Data Type: float32
Float64 Array: [1.1 2.2 3.3] | Data Type: float64
Default Complex Array: [1.+2.j 3.+4.j] | Data Type: complex128
Complex64 Array: [1.+2.j 3.+4.j] | Data Type: complex64
Complex128 Array: [1.+2.j 3.+4

## Creating and formating Arrays from existing data 
- asarray	Converts input data to a NumPy array	[1. 2. 3. 4.]
- frombuffer	Converts binary data to a NumPy array	['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o'...]
- fromiter	Creates an array from an iterable	[0 1 2 3 4]
- arange	Creates evenly spaced values in a range	[0 2 4 6 8]
- linspace	Creates evenly spaced values between two points	[ 0. 2.5 5. 7.5 10. ]
l- ogspace	Creates logarithmically spaced values	[ 10. 31.6 100. 316.2 1000.]

In [12]:
# numpy.asarray: Converts input data to an ndarray
python_list = [1, 2, 3, 4]
asarray_example = np.asarray(python_list, dtype=np.float64)
print("Using numpy.asarray:")
print(asarray_example)

# numpy.frombuffer: Interprets a buffer as a 1-dimensional array
buffer = b'Hello World'
frombuffer_example = np.frombuffer(buffer, dtype='S1')
print("\nUsing numpy.frombuffer:")
print(frombuffer_example)

# numpy.fromiter: Creates an array from an iterable
iterable = range(5)
fromiter_example = np.fromiter(iterable, dtype=int)
print("\nUsing numpy.fromiter:")
print(fromiter_example)

# numpy.arange: Creates an array of evenly spaced values within a given range
arange_example = np.arange(0, 10, 2)
print("\nUsing numpy.arange:")
print(arange_example)

# numpy.linspace: Creates an array of evenly spaced values between two numbers
linspace_example = np.linspace(0, 10, 5)
print("\nUsing numpy.linspace:")
print(linspace_example)

# numpy.logspace: Creates an array of logarithmically spaced values
logspace_example = np.logspace(1, 3, 5, base=10.0)
print("\nUsing numpy.logspace:")
print(logspace_example)


Using numpy.asarray:
[1. 2. 3. 4.]

Using numpy.frombuffer:
[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']

Using numpy.fromiter:
[0 1 2 3 4]

Using numpy.arange:
[0 2 4 6 8]

Using numpy.linspace:
[ 0.   2.5  5.   7.5 10. ]

Using numpy.logspace:
[  10.           31.6227766   100.          316.22776602 1000.        ]


## Broadcasting

In [17]:
# Broadcasting example - 1
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

# Broadcasting addition
result = a + b
print("Broadcasting result:")
print(result)

# Broadcasting example - 2
c = np.array([[ 0.0, 0.0, 0.0],[10.0,10.0,10.0],
 [20.0,20.0,20.0],[30.0,30.0,30.0]])
d = np.array([1.0,2.0,3.0])
print ('First array:', c)
print ('\n')
print ('Second array:', d)
print ('\n')
print ('First Array + Second Array', c+d)

Broadcasting result:
[[2 3 4]
 [3 4 5]
 [4 5 6]]
First array: [[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array: [1. 2. 3.]


First Array + Second Array [[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


## Mathematical Operations

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Basic math operations
print("Original array:")
print(arr)

print("\nArray squared:")
print(arr ** 2)

print("\nSum of all elements:", arr.sum())
print("Mean of all elements:", arr.mean())
print("Maximum element:", arr.max())


## Reshaping and Transposing

In [ ]:

# Reshape
arr = np.arange(12).reshape(3, 4)
print("Reshaped array:")
print(arr)

# Transpose
transposed = arr.T
print("\nTransposed array:")
print(transposed)


## Stacking and Splitting

In [ ]:

# Horizontal and vertical stacking
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stack arrays
hstacked = np.hstack((a, b))
vstacked = np.vstack((a, b))

print("Horizontally stacked array:")
print(hstacked)

print("\nVertically stacked array:")
print(vstacked)


## Statistical Functions

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Original array:")
print(arr)

print("\nMinimum value:", np.amin(arr))
print("Maximum value:", np.amax(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))


## Sort, Search and Counting functions in numpy
- sort	Sorts the array	[1, 2, 5, 7, 9]
- argsort	Indices that would sort the array	[3, 1, 0, 4, 2]
- argmax	Index of the maximum value	2
- argmin	Index of the minimum value	3
- where	Indices where condition is met	(array([2, 4]),)
- nonzero	Indices of non-zero elements	(array([0, 1, 2, 3, 4]),)
- unique	Finds unique elements and counts	[1, 2, 5, 7, 9], [1, 1...]
- count_nonzero	Counts the number of non-zero elements	5

In [ ]:
# Sample array for demonstration
arr = np.array([5, 2, 9, 1, 7])

### 1. Sorting Functions
# numpy.sort: Returns a sorted copy of the array
sorted_array = np.sort(arr)
print("Sorted Array:")
print(sorted_array)

# numpy.argsort: Returns the indices that would sort the array
sorted_indices = np.argsort(arr)
print("\nIndices to Sort Array:")
print(sorted_indices)

# Sort along a specific axis (2D example)
arr_2d = np.array([[8, 4, 2], [3, 9, 1]])
sorted_2d = np.sort(arr_2d, axis=1)
print("\n2D Array Sorted Row-wise:")
print(sorted_2d)

### 2. Searching Functions
# numpy.argmax: Returns the index of the maximum element
max_index = np.argmax(arr)
print("\nIndex of Maximum Value:")
print(max_index)

# numpy.argmin: Returns the index of the minimum element
min_index = np.argmin(arr)
print("\nIndex of Minimum Value:")
print(min_index)

# numpy.where: Returns the indices of elements satisfying a condition
condition_indices = np.where(arr > 5)
print("\nIndices Where Elements > 5:")
print(condition_indices)

# numpy.nonzero: Returns indices of non-zero elements
non_zero_indices = np.nonzero(arr)
print("\nIndices of Non-zero Elements:")
print(non_zero_indices)

### 3. Counting Functions
# numpy.unique: Finds unique elements and their counts
unique_elements, counts = np.unique(arr, return_counts=True)
print("\nUnique Elements and Counts:")
print("Elements:", unique_elements)
print("Counts:", counts)

# numpy.count_nonzero: Counts the number of non-zero elements
non_zero_count = np.count_nonzero(arr)
print("\nCount of Non-zero Elements:")
print(non_zero_count)


Sorted Array:
[1 2 5 7 9]

Indices to Sort Array:
[3 1 0 4 2]

2D Array Sorted Row-wise:
[[2 4 8]
 [1 3 9]]

Index of Maximum Value:
2

Index of Minimum Value:
3

Indices Where Elements > 5:
(array([2, 4]),)

Indices of Non-zero Elements:
(array([0, 1, 2, 3, 4]),)

Unique Elements and Counts:
Elements: [1 2 5 7 9]
Counts: [1 1 1 1 1]

Count of Non-zero Elements:
5


## Matrix operations in Numpy
- Addition	+	A + B
- Subtraction	-	A - B
- Element-wise Multiply	*	A * B
- Element-wise Division	/	A / B
- Matrix Multiplication	np.dot or @	np.dot(A, B)
- Transpose	np.transpose	np.transpose(A)
- Inverse	np.linalg.inv	np.linalg.inv(A)
- Determinant	np.linalg.det	np.linalg.det(A)
- Eigenvalues	np.linalg.eig	np.linalg.eig(A)
- Identity Matrix	np.eye	np.eye(n)
- Rank	np.linalg.matrix_rank	np.linalg.matrix_rank(A)

In [ ]:
# Create two example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Display the matrices
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

### 1. Basic Matrix Operations
# Addition
C_add = A + B
print("\nMatrix Addition (A + B):")
print(C_add)

# Subtraction
C_sub = A - B
print("\nMatrix Subtraction (A - B):")
print(C_sub)

# Element-wise Multiplication
C_mul = A * B
print("\nElement-wise Multiplication (A * B):")
print(C_mul)

# Element-wise Division
C_div = A / B
print("\nElement-wise Division (A / B):")
print(C_div)

### 2. Matrix Multiplication
C_matmul = np.dot(A, B)  # or use A @ B
print("\nMatrix Multiplication (A dot B):")
print(C_matmul)

### 3. Transpose
A_transpose = np.transpose(A)
print("\nTranspose of A:")
print(A_transpose)

### 4. Matrix Inverse
A_inverse = np.linalg.inv(A)
print("\nInverse of A:")
print(A_inverse)

### 5. Determinant
A_determinant = np.linalg.det(A)
print("\nDeterminant of A:")
print(A_determinant)

### 6. Eigenvalues and Eigenvectors
A_eigenvalues, A_eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(A_eigenvalues)
print("Eigenvectors of A:")
print(A_eigenvectors)

### 7. Identity Matrix
I = np.eye(2)
print("\nIdentity Matrix (2x2):")
print(I)

### 8. Matrix Rank
A_rank = np.linalg.matrix_rank(A)
print("\nRank of A:")
print(A_rank)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Addition (A + B):
[[ 6  8]
 [10 12]]

Matrix Subtraction (A - B):
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication (A * B):
[[ 5 12]
 [21 32]]

Element-wise Division (A / B):
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Matrix Multiplication (A dot B):
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of A:
-2.0000000000000004

Eigenvalues of A:
[-0.37228132  5.37228132]
Eigenvectors of A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Identity Matrix (2x2):
[[1. 0.]
 [0. 1.]]

Rank of A:
2
